dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.9.3

compiler:
  solc:
    remappings:
      - "@openZeppelin=OpenZeppelin/openzeppelin-contracts@4.9.3"

dotenv: .env

networks:
  default: Sepolia
  Sepolia:
    verify: True
  development:
    verify: False

wallets:
  key0: ${PRIVATE_KEY_0}
